# Generated by Django 5.1.5 on 2025-02-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('feature', 'Feature'), ('gallery', 'Gallery')], default='article', max_length=100),
        ),
    ]
