# Generated by Django 5.1.5 on 2025-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('feature', 'Feature'), ('gallery', 'Gallery'), ('video', 'Video'), ('slider', 'Slider'), ('image', 'Image')], default='article', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
