# Generated by Django 5.1.5 on 2025-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_content_content_type_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
